version: '3.8'

services:
  paciente:
    build:
      context: ./SecretariaSaludPaciente
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - secretaria-salud-network
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=secretaria_salud
      - DATABASE_USER=root
      - DATABASE_PASSWORD=

  medico:
    build:
      context: ./SecretariaSaludMedico
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - secretaria-salud-network
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=secretaria_salud
      - DATABASE_USER=root
      - DATABASE_PASSWORD=

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: secretaria_salud
    ports:
      - "3306:3306"
    networks:
      - secretaria-salud-network

networks:
  secretaria-salud-network:
    driver: bridge
